language: python
python:
  - "3.6"
install:
    - pip install -r requirements.txt
    - pip install coveralls
# env:
# - DB=sqlite
# - DB=mysql
# - DB=postgres
# addons:
# postgresql: "9.4"
script:
  - echo foo
  - coverage run --omit=*Unittests_for_Accommodation_App.py* docopt_main.py Dojo_class.py
# --source=hc
after_success: coveralls
cache: pip
notifications:
  slack: andela:ckqdCeo8WuWg0dABDHQhAFQp
